global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8085']
    metrics_relabel_configs:
      - source_labels: [__name__]
        regex: '(jvm_memory_used|system_cpu_usage|http_server_requests_seconds_.*)'
        action: keep
